### ISSUE TITLE
scraper stuck in loop searching for thumbnails

### ISSUE THREAD

**Issue by giovsta** [pruthvik00911/google-images-scraper#3]
Now it works, even been able to do everything a few times. Most times however, it gets stuck in a loop where it keeps scroling even when the pages are at the end, and keeps printing statements on how many thumbnails it found.
![image](https://github.com/pruthvik00911/google-images-scraper/assets/64974621/af8d89cf-bca1-4d86-ba6a-b655c9ad480a)

**Comment by pruthvik-sheth** [comment]
Can you provide me your config.yaml file? So that I can replicate the same issue.

**Comment by giovsta** [comment]
sender_email: ""
receiver_email: ""
sender_email_password: ""

csv_path: "./csv_downloads"
image_path: "./image_downloads"

search_queries:
  - Silvio Berlusconi

images_limit: 1000

It did the same with 500 before

**Comment by giovsta** [comment]
I've tried now with 300, and it starts fetching link in that case

**Comment by pruthvik-sheth** [comment]
I've checked and found that a silly edge case wasn't handled. It is fixed now, you can pull the new changes. Thanks for noticing!
