### ISSUE TITLE
Suggested feature: using multiple instances of image search to execute multiple search_queries at the same time

### ISSUE THREAD

**Issue by giovsta** [pruthvik00911/google-images-scraper#4]
In a few words, if person_1 and person_2 are in my search queries, why not allow the script to run 2 windows looking for person_1 images and 2 windows for person_2? is this possible and easy to implement?

**Comment by pruthvik-sheth** [comment]
It is possible to implement it. However, we are already running the person_1 on 5 threads (Which you can configure btw). So if you want to increase the speed you can change the number of threads to say 10 or as per your system. Thus, perhaps the script will take the same amount of time to run on both the cases i.e. If you run 10 threads per single search query or you use 2 instances and use 5 threads for each.

**Comment by giovsta** [comment]
it is just that at the moment the 5 sessions opened scroll over the same images. I don't know if this is just what appears in the interface and it is actually scraping different thumbnails, but it does not seem so at the moment. Even running only one instance gives the same results in roughly the same time to me.

**Comment by pruthvik-sheth** [comment]
It is true that same thing appears on all of the 5 sessions however, a locking mechanism is implemented which ensures synchronisation between all the 5 threads. So each and every instance scrolls to load thumbnails but, when it comes to gathering links each and every instance clicks on different thumbnail and collects the links.
